### ISSUE TITLE
python2.7で Resaspy(resas_key) を実行すると実行エラー

### ISSUE THREAD

**Issue by KTaskn** [ar90n/resaspy#1]
Python 2.7.12で実行した場合に実行エラーが発生しました

# 実行コード
``` hello_resas.py
from resaspy import Resaspy
import os
resas_key = "<api_key>"
resaspy = Resaspy(resas_key)
resaspy.prefectures()
```

# エラー内容
```
Traceback (most recent call last):
  File "resas_util.py", line 4, in <module>
    resaspy = Resaspy(resas_key)
  File "/usr/local/lib/python2.7/site-packages/resaspy/resaspy.py", line 91, in __init__
    super( Resaspy, self ).__init__( accessor )
TypeError: super() argument 1 must be type, not classobj
```

**Comment by ar90n** [comment]
申し訳ありません．python3系のみ対応です．

**Comment by KTaskn** [comment]
承知しました。
お早い回答ありがとうございます。
